# dev only
-
  environment:
    package_semantic_version: 0.0.1
  version: $(package_semantic_version).{build}
  branches:
    only:
    - dev
    - master
  skip_tags: true
  skip_commits:
    files:
      - .editorconfig
      - .gitattributes
      - .gitignore
      - appveyor.yml
      - LICENSE
      - README.md
      - Settings.StyleCop
      - Yarm.CLI.sln
      - Yarm.CLI.sln.DotSettings
      - '**/*.csproj'
      - samples/
  image: Visual Studio 2017
  configuration: Debug
  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '$(package_semantic_version)'
    package_version: '$(package_semantic_version)'
  nuget:
    disable_publish_on_pr: true
  build_script:
  - ps: dotnet --version
  - ps: dotnet restore
  - ps: dotnet build -c $env:configuration -v minimal
  test_script:
  - ps: dotnet test test/Yarm.ConsoleApp.Tests -c $env:configuration

# release/all
-
  environment:
    package_semantic_version: 0.0.1
    project_name: yarm-cli
    publish_output: published
  version: $(package_semantic_version).{build}
  pull_requests:
    do_not_increment_build_number: true
  branches:
    only:
    - release/all
  skip_tags: true
#  skip_commits:
#    files:
#      - .editorconfig
#      - .gitattributes
#      - .gitignore
#      - appveyor.yml
#      - LICENSE
#      - README.md
#      - Settings.StyleCop
#      - Yarm.CLI.sln
#      - Yarm.CLI.sln.DotSettings
#      - '**/*.csproj'
#      - samples/
  image: Visual Studio 2017
  configuration: Release
  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '$(package_semantic_version)'
    package_version: '$(package_semantic_version)'
  nuget:
    disable_publish_on_pr: true
  build_script:
  - ps: dotnet --version
  - ps: dotnet restore
  - ps: dotnet build -c $env:configuration -v minimal
  - ps: dotnet publish src/Yarm.ConsoleApp -c $env:configuration -o $env:publish_output -v minimal
  test_script:
  - ps: dotnet test test/Yarm.ConsoleApp.Tests -c $env:configuration
  artifacts:
  - path: $(publish_output)
    name: $(project_name)-$(package_semantic_version)
    type: zip
  # deploy:
  # - provider: Environment
  #   name: GitHub Release for YARM CLI
